Feature/4 new type result image
mathieumack/Orion.net pull request #13
Opened 2020-01-14 12:51 UTC by SANHNV

from existant image in Client, sent in base64 to API and display in UI javascript

2020-01-15 15:57 UTC, mathieumack requested changes

2020-01-15 15:57 UTC, mathieumack commented on Orion.Net.Scripts.Common/Diagnostics/TakeScreenShotClientScript.cs
> +                await SendStringContent("parameter invalid. Screenshot not taken.");
Please remove these lines and keep only one call.

2020-01-15 15:57 UTC, mathieumack commented on Orion.Net.Scripts.Common/Diagnostics/TakeScreenShotClientScript.cs
> +                string testPath = @"C:\Users\cadier\Downloads\Logoeconocom.jpg";
Please remove all reference to local storage on your laptop

2020-01-15 15:57 UTC, mathieumack commented on Orion.Net.Scripts.Common/Diagnostics/TakeScreenShotClientScript.cs
> +                string testPath = @"C:\Users\cadier\Downloads\Logoeconocom.jpg";
And use the correct file path sended as argument ;)

2020-01-15 21:31 UTC, mathieumack requested changes

2020-01-15 21:31 UTC, mathieumack commented on Orion.Net.Scripts.Common/Diagnostics/SendImageContentClientScript.cs
> +                await SendStringContent("Image sent.");
Is it needed ?
Please remove it as it's more log information than usefulle information for this script.

2020-01-15 21:31 UTC, mathieumack commented on Orion.Net.Scripts.Common/Diagnostics/SendImageContentClientScript.cs
> +                await SendStringContent("parameter invalid. Image not found.");
Please keep only one line. Not 4.

2020-01-15 21:31 UTC, mathieumack commented on Orion.Net.Scripts.Common/Diagnostics/SendImageContentClientScript.cs
> +            if (parameter == null || parameter.ParameterName != "sendImage")
To be discussed, we can do it in the BaseClientScript in order to create a generic method and check parameters at each start of Execute method.

2020-01-16 11:34 UTC, mathieumack requested changes

2020-01-16 11:34 UTC, mathieumack commented on Orion.Net.Client/Scripts/BaseClientScript.cs
> +        protected async Task SendImageContent(string pathImage)
Could you add a little summary in order to describe the behaviour

2020-01-16 11:34 UTC, mathieumack commented on Orion.Net.Core/Interfaces/ClientScriptResultType.cs
> +        /// byte[], base64
byte[] or base64?

2020-01-16 11:34 UTC, mathieumack commented on Orion.Net.Core/Results/ImageContentResult.cs
> +        public byte[] ImageInByteArray { get; set; }
Image**As**ByteArray

2020-01-16 21:34 UTC, HisCodeness commented on Orion.Net.Scripts.Common/Diagnostics/SendImageContentClientScript.cs
> +                Name = "filePath"
You can create a private constant for this parameter name, this will avoid repeating hard coded string

2020-01-16 21:36 UTC, mathieumack requested changes

2020-01-16 21:36 UTC, mathieumack commented on Orion.Net.Client/Configuration/Connector.cs
> +            HttpContent content = new StringContent(JsonConvert.SerializeObject(result), Encoding.UTF8, "application/json");
Please keep the new StringContent in the switch case as some case could generate Something else than a StringContent object.

2020-01-16 21:36 UTC, mathieumack commented on Orion.Net.Client/Scripts/BaseClientScript.cs
> -            // Manage start script :
Please keep this comment, it prepare a next evolution ;).

2020-01-16 21:36 UTC, mathieumack commented on Orion.Net.Client/Scripts/BaseClientScript.cs
> -            // Notifiy end script
Please keep this comment, it prepare a next evolution ;).

2020-01-16 21:36 UTC, mathieumack commented on Orion.Net.Client/Scripts/BaseClientScript.cs
> +        {
Please add some checks about the pathImage
null, StringOrWhitespace or perhaps that the file does not exists

2020-01-17 09:47 UTC, mathieumack approved these changes

2020-01-17 09:48 UTC, merged